global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mysawit-spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          instance: 'local'
      - targets: ['107.23.124.17.nip.io']
        labels:
          instance: 'production'
